CREATE TABLE [User] (
	DBKey		INT IDENTITY(1,1),
	Login		NVARCHAR(50) NOT NULL,
	Password	BINARY(64) NOT NULL,
	DBKeyRole		INT NOT NULL,
	CONSTRAINT PK_User PRIMARY KEY (DBKey),
	CONSTRAINT FK_User_Role FOREIGN KEY (DBKeyRole) REFERENCES [Role] (DBKey)
)

--INSERT INTO [User] VALUES('Admin', HASHBYTES('SHA2_512', '12345a'), 1);
--INSERT INTO [User] VALUES('User', HASHBYTES('SHA2_512', '12345u'), 2);

SELECT * FROM [User]

--DROP TABLE [User]